//
// Created by errant on 17/04/24.
//

#ifndef ASIGNACIONDINAMICAMEMORIAPORINCREMENTOS_2023_2_ASIGNACIONDINAMICAMEMORIAEXACTA_HPP
#define ASIGNACIONDINAMICAMEMORIAPORINCREMENTOS_2023_2_ASIGNACIONDINAMICAMEMORIAEXACTA_HPP
#include <iostream>
#include <iomanip>
#include <fstream>
#include <cstring>

#define INCREMENTO 5
using namespace std;


#endif //ASIGNACIONDINAMICAMEMORIAPORINCREMENTOS_2023_2_ASIGNACIONDINAMICAMEMORIAEXACTA_HPP
